### ISSUE TITLE
How to test a bean that expects multiple constraint violations?

### ISSUE THREAD

**Issue by erizzo** [jinahya/assertj-bean-validation#2]
I want to test a multi-violation scenario. For example, 2 different properties of a bean are both invalid. In that case, The `Set<ConstraintViolation>` that results from validation will have 2 `ConstraintViolation`s in it, but the `Consumer` I can pass to `BeanAssert.isValid()` only gets 1 at a time. Is there a technique to check that _both_ expected violations are present in the `Set`?

**Comment by erizzo** [comment]
Now that I tried some test code, I'm even more confused. Can I not write negative test cases - ones where the bean I'm testing is expected to have validation errors?

**Comment by onacit** [comment]
Thank you for the report. Let me see what I can do for the case.

**Comment by onacit** [comment]
@erizzo Sorry I'm late.

Can you please check the `0.2.0`?

Coordinates and APIs changed.

```xml
<groupId>com.github.jinahya</groupId>
<artifactId>assertj-bean-validation</artifactId>
<version>0.2.0</version>
<!--classifier></classifier--> <!-- See the README -->
<scope>test</scope>
```

```java
assertThatBean(bean)
        .consumingViolations(cv -> {
        })
        .isValid()
;
```
